name: cross_entropy_agent_sweep_p1
method: grid
metric:
  goal: maximize
  name: Evaluation/Mean_Total_Reward
parameters:
  env:
    values: ["Taxi-v3"]
  train:
    values: [true]
  trajectory_n:
    values: [100, 200, 300, 400, 500, 600]
  iteration_n:
    values: [200, 400, 600, 800, 1000]
  gamma_q:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  max_trajectory_len:
    values: [50, 100, 150, 200]