name: cross_entropy_agent_sweep
method: grid
metric:
  goal: maximize
  name: Evaluation/Mean_Total_Reward
parameters:
  env:
    values: ["Taxi-v3"]
  train:
    values: [true]
  trajectory_n:
    values: [500, 1000, 1500, 2000, 2500, 3000]
  iteration_n:
    values: [200, 400, 600, 800, 1000]
  gamma_q:
    values: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
  max_trajectory_len:
    values: [100, 500, 1000, 1500, 2000]