name: cross_entropy_agent_sweep_p4
method: grid
metric:
  goal: maximize
  name: Evaluation/Mean_Total_Reward
parameters:
  env:
    values: ["Taxi-v3"]
  train:
    values: [true]
  laplace_f: 
    values: [0.0, 0.5, 1.0]
  policy_f: 
    values: [1.0, 0.5, 0.0]    
  trajectory_n:
    values: [2000, 1000, 100]
  iteration_n:
    values: [25]
  gamma_q:
    values: [0.1, 0.3, 0.5]
  max_trajectory_len:
    values: [200]
  num_policy_samples:
    values: [1, 3]